use std::{
    collections::BTreeSet,
    env, fs,
    io::Write as _,
    path::{Path, PathBuf},
};

use fluent_syntax::parser;
use unic_langid::LanguageIdentifier;

/// A builder to configure and generate the static cache code for `fluent-zero`.
pub struct FluentZeroBuilder {
    locales_dir: PathBuf,
    charset_dest: Option<PathBuf>,
}

impl FluentZeroBuilder {
    /// Creates a new builder pointing to the directory containing locale subdirectories.
    #[must_use]
    pub fn new<P: AsRef<Path>>(locales_dir_path: P) -> Self {
        Self {
            locales_dir: locales_dir_path.as_ref().to_path_buf(),
            charset_dest: None,
        }
    }

    /// Opt-in to exporting a deterministic text file containing all unique
    /// characters used across all `.ftl` files. This is highly recommended
    /// for font subsetting in WASM/Game GUI environments.
    #[must_use]
    pub fn export_charset<P: AsRef<Path>>(mut self, dest: P) -> Self {
        self.charset_dest = Some(dest.as_ref().to_path_buf());
        self
    }

    /// Consumes the builder, parses the Fluent files, and generates the Rust code.
    #[allow(clippy::too_many_lines)]
    pub fn generate(self) {
        println!("cargo:rerun-if-changed={}", self.locales_dir.display());

        let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
        let dest_path = Path::new(&out_dir).join("static_cache.rs");
        let mut file = fs::File::create(&dest_path).expect("Failed to create static_cache.rs");

        writeln!(&mut file, "// @generated by fluent-zero-build").unwrap();

        if !self.locales_dir.exists() {
            return;
        }

        let mut bundle_entries: Vec<(String, String)> = Vec::new();
        let mut cache_root_entries: Vec<(String, String)> = Vec::new();

        // This BTreeSet guarantees the output characters are sorted and deterministic.
        let mut unique_chars: BTreeSet<char> = BTreeSet::new();

        for entry in fs::read_dir(&self.locales_dir).unwrap() {
            let entry = entry.unwrap();
            let path = entry.path();

            if path.is_dir() {
                let dir_name = path.file_name().unwrap().to_str().unwrap();
                let lang_id: LanguageIdentifier = match dir_name.parse() {
                    Ok(id) => id,
                    Err(_) => continue,
                };
                let lang_key = lang_id.to_string();
                let sanitized_lang = lang_key.replace('-', "_").to_uppercase();

                // Define variable names
                let cache_name = format!("CACHE_{sanitized_lang}");
                let bundle_name = format!("BUNDLE_{sanitized_lang}");

                let mut combined_ftl_source = String::new();
                // Vector of (Key, ValueCode)
                let mut cache_entries: Vec<(String, String)> = Vec::new();

                for file_entry in fs::read_dir(&path).unwrap() {
                    let file_entry = file_entry.unwrap();
                    let file_path = file_entry.path();

                    if file_path.extension().is_some_and(|ext| ext == "ftl") {
                        println!("cargo:rerun-if-changed={}", file_path.display());
                        let source = fs::read_to_string(&file_path).unwrap();
                        combined_ftl_source.push_str(&source);
                        combined_ftl_source.push('\n');

                        let ast = parser::parse(source).expect("Failed to parse FTL");
                        for entry in ast.body {
                            if let fluent_syntax::ast::Entry::Message(msg) = entry {
                                // 1. Character Harvesting for Subsetting
                                if let Some(pattern) = &msg.value {
                                    for element in &pattern.elements {
                                        if let fluent_syntax::ast::PatternElement::TextElement {
                                            value,
                                        } = element
                                        {
                                            for ch in value.chars() {
                                                // Ignore invisible control characters
                                                if !ch.is_control() {
                                                    unique_chars.insert(ch);
                                                }
                                            }
                                        }
                                    }
                                }

                                // 2. Cache Entry Generation
                                // Check if Simple Static
                                // Criteria:
                                // 1. Has a value.
                                // 2. Only one element in the pattern.
                                // 3. That element is Text (not a Variable).
                                // 4. No escape characters (simplifies generation).
                                if let Some(pattern) = &msg.value
                                    && pattern.elements.len() == 1
                                    && let fluent_syntax::ast::PatternElement::TextElement { value } =
                                        &pattern.elements[0]
                                    && !value.contains('\\')
                                {
                                    // Entry::Static("value")
                                    // Stored directly in the binary .rodata
                                    cache_entries.push((
                                        msg.id.name.clone(),
                                        format!("::fluent_zero::CacheEntry::Static(\"{value}\")"),
                                    ));
                                } else {
                                    // Entry::Dynamic
                                    // Requires parsing by FluentBundle at runtime
                                    cache_entries.push((
                                        msg.id.name.clone(),
                                        "::fluent_zero::CacheEntry::Dynamic".to_string(),
                                    ));
                                }
                            }
                        }
                    }
                }

                // 1. Write the Bundle Static Item
                // We use LazyLock to ensure we only parse the FTL for the bundle if we actually
                // hit a dynamic message for this specific locale.
                let escaped_ftl = format!("{combined_ftl_source:?}");
                let bundle_init_code = format!(
                    "std::sync::LazyLock::new(|| {{
                    let lang: ::fluent_zero::LanguageIdentifier = \"{lang_key}\".parse().unwrap();
                    let mut bundle = ::fluent_zero::ConcurrentFluentBundle::new_concurrent(vec![lang]); 
                    let res = ::fluent_zero::FluentResource::try_new({escaped_ftl}.to_string()).expect(\"FTL Error\");
                    bundle.add_resource(res).expect(\"Resource Error\");
                    bundle
                }})"
                );

                writeln!(&mut file,
                    "static {bundle_name}: std::sync::LazyLock<::fluent_zero::ConcurrentFluentBundle<::fluent_zero::FluentResource>> = {bundle_init_code};"
                ).unwrap();

                bundle_entries.push((lang_key.clone(), format!("&{bundle_name}")));

                // 2. Write Unified Cache Map
                let mut map = phf_codegen::Map::new();
                map.phf_path("::fluent_zero::phf");
                for (k, v) in &cache_entries {
                    map.entry(k.as_str(), v.as_str());
                }

                writeln!(
                    &mut file,
                    "static {}: ::fluent_zero::phf::Map<&'static str, ::fluent_zero::CacheEntry> = {};",
                    cache_name,
                    map.build()
                )
                .unwrap();
                cache_root_entries.push((lang_key.clone(), cache_name));
            }
        }

        // 3. Generate Root Maps

        // Unified Cache Root
        let mut root_map = phf_codegen::Map::new();
        root_map.phf_path("::fluent_zero::phf");
        for (l, v) in &cache_root_entries {
            root_map.entry(l.as_str(), format!("&{v}"));
        }
        writeln!(&mut file,
            "pub static CACHE: ::fluent_zero::phf::Map<&'static str, &'static ::fluent_zero::phf::Map<&'static str, ::fluent_zero::CacheEntry>> = {};",
            root_map.build()
        ).unwrap();

        // Locales Root
        let mut bundle_map = phf_codegen::Map::new();
        bundle_map.phf_path("::fluent_zero::phf");
        for (l, c) in &bundle_entries {
            bundle_map.entry(l.as_str(), c.as_str());
        }
        writeln!(&mut file,
            "pub static LOCALES: ::fluent_zero::phf::Map<&'static str, &'static std::sync::LazyLock<::fluent_zero::ConcurrentFluentBundle<::fluent_zero::FluentResource>>> = {};",
            bundle_map.build()
        ).unwrap();

        // 4. Export Charset (If Requested)
        if let Some(charset_dest) = self.charset_dest {
            let charset_string: String = unique_chars.into_iter().collect();
            fs::write(&charset_dest, charset_string).expect("Failed to write fluent charset file");

            // Tell cargo to rerun if the output path changes, though
            // typically OUT_DIR contents are ignored.
            println!("cargo:rerun-if-changed={}", charset_dest.display());
        }
    }
}

/// Generates the static cache code for `fluent-zero`.
///
/// This is the legacy, non-breaking function signature. Under the hood,
/// it delegates to `FluentZeroBuilder`.
///
/// # Arguments
///
/// * `locales_dir_path` - Relative path to the folder containing locale subdirectories.
pub fn generate_static_cache(locales_dir_path: &str) {
    FluentZeroBuilder::new(locales_dir_path).generate();
}
